addon_backup_db_create:
    pattern: /create/{name}
    defaults: { _controller: AddonBackupBundle:Db:dbcreate,name:name }

addon_backup_db_dump:
    pattern: /dump/{name}
    defaults: { _controller: AddonBackupBundle:Db:dbdump,name:name}

addon_backup_db_dump_form:
    pattern: /dumpform/{pass}
    defaults: { _controller: AddonBackupBundle:Db:dbdumpform,pass:pass}
    
addon_backup_db_create_form:
    pattern: /createform/{pass}
    defaults: { _controller: AddonBackupBundle:Db:dbcreateform,pass:pass}
    
addon_backup_dump_upload:
    pattern: /dumpupload
    defaults: { _controller: AddonBackupBundle:Db:dumpupload}
    
addon_backup_dump_create:
    pattern: /dumpcreate
    defaults: { _controller: AddonBackupBundle:Db:dumpcreate}
