parameters:
#    addon_backup.example.class: Addon\BackupBundle\Example

services:
#    addon_backup.example:
#        class: %addon_backup.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
