<?php

namespace Cinema\CinemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cinema\CinemaBundle\CinemaCinemaBundle;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnipetRepository extends EntityRepository
{
   
    /**
     * get All snipets
     * @return array Array of objects Snipet
     **/
    public function getAllSnipets()
    {
        $snipets = $this->findAll();
        if ( !$snipets ) return false;
        return $snipets;
    }//end func
    
    
     
}
