Cinema\CinemaBundle\Entity\Schedule:
    type: entity
    table: schedule
    repositoryClass: Cinema\CinemaBundle\Entity\ScheduleRepository
   
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        film_id:
            type: integer
            nullable: false
        time_begin:
            type: datetime
            nullable: false
        price:
            type: integer
            nullable: true
        numberRoot:
            column: number_room
            type: integer
            nullable: true
        is3d:
            type: boolean
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
           
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]