Cinema\CinemaBundle\Entity\Snipet:
    type: entity
    table: snipet
    repositoryClass: Cinema\CinemaBundle\Entity\SnipetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        key:
            column: key_text
            type: string
            length: '255'
            nullable: true
        desc:
            column: describe_
            type: string
            length: '255'
            nullable: true 
        snipet:
            column: snipet_text
            type: text
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]